# Site settings
title: Labor Tubs Northwest
email: april@labortubs.com
description: > # this means to ignore newlines until "baseurl:"
        Copyright &copy; Labor Tubs Northwest 2016
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://labortubs.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink:    /blog/:year/:month/:day/:title/